name: telegram-video-forward-bot
services:
  - name: bot
    docker:
      image: python:3.11-slim
      args:
        - name: PYTHON_VERSION
          value: "3.11"
    ports:
      - port: 8080
        protocol: http
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "YOUR_BOT_TOKEN"
      - name: MONGO_URI
        value: "YOUR_MONGODB_URI"
      - name: DATABASE_NAME
        value: "telegram_video_bot"
      - name: AUTO_THUMBNAIL
        value: "true"
      - name: CHECK_DUPLICATES
        value: "true"
      - name: DELETE_DUPLICATES
        value: "true"
      - name: MAX_FILE_SIZE
        value: "2000000000"
    regions:
      - fra  # Frankfurt
      - nyc  # New York
    instance:
      type: nano
    health_checks:
      http:
        path: /
        port: 8080
        interval: 30s
        timeout: 5s
    build:
      dockerfile: Dockerfile
