name: telegram-video-bot
services:
  - name: bot
    docker:
      image: python:3.11-slim
    ports:
      - port: 8080
        protocol: http
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "your_bot_token"
      - name: MONGO_URI
        value: "your_mongodb_uri"
    routes:
      - path: /
        port: 8080
    instance:
      type: nano
    regions:
      - fra
    build:
      dockerfile: Dockerfile
    health_checks:
      http:
        path: /health
        port: 8080
        interval: 30s
